### ISSUE TITLE
Link to cheap alternative for "Tag Connect TC2050-IDC-NL" is broken

### ISSUE THREAD

**Issue by fgeck** [toniebox-reverse-engineering/toniebox-reverse-engineering.github.io#8]
Hi,

I would like to purchase the cheaper verison of "[Tag Connect TC2050-IDC-NL](https://www.tag-connect.com/product/tc2050-idc-nl-10-pin-no-legs-cable-with-ribbon-connector)" unfortunately the link to aliexpress is broken. 

Thanks and best regards

**Comment by SciLor** [comment]
You may search for 2x5 1,27mm debug probe. But you already found an alternative on aliexpress I see
